{
  diagnosticLoggerEntries: [
    {
      Level: error,
      Message: Reentrant log event detected. Logging when inside the scope of another log event can cause a StackOverflowException. LogEventInfo.Message:message from OnEvaluating
    }
  ],
  Envelopes: [
    {
      Header: {
        event_id: Guid_1,
        sdk: {
          name: sentry.dotnet
        },
        trace: {
          environment: production,
          public_key: d4d82fc1c2c4032a83f3a29aa3a3aff,
          release: test-release,
          trace_id: Guid_2
        }
      },
      Items: [
        {
          Header: {
            type: event
          },
          Payload: {
            Source: {
              Message: {
                Message: message,
                Formatted: message
              },
              Logger: Sentry.NLog.Tests.IntegrationTests,
              Platform: csharp,
              Level: error,
              Request: {},
              Contexts: {
                trace: {
                  Operation: 
                }
              },
              User: {
                IpAddress: {{auto}}
              },
              Environment: production
            }
          }
        }
      ]
    }
  ]
}